language: scala
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt
script:
  - cd relay-web-examples && npm install; cd ..
  - sbt -J-Xmx3g -v -d "set concurrentRestrictions in Global := Seq(Tags.limitAll(2))" test
after_success:
  - sbt publish
